# 项目相关配置
shopping:
  # 名称
  name: shopping-xtxr
  # 版本
  version: 3.8.2
  # 版权年份
  copyrightYear: 2022
  # 实例演示开关
  demoEnabled: false
  # 文件路径 示例（ Windows配置D:/qgj/uploadPath，Linux配置 /home/qgj/uploadPath）
  profile: D:/shopping-img/uploadPath
  # 获取ip地址开关
  addressEnabled: true
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 1001
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.qgj: debug
    org.springframework: warn

# Spring配置
spring:
  jackson:
    default-property-inclusion: non_null
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid,config
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: false
  # redis 配置
  redis:
    # 地址
    #    host: localhost
    # 端口，默认为6379
    host: 175.178.98.49
    port: 6379
    # 数据库索引
    database: 1
    # 密码
    password: 123456
    #    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
      servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  mail:
    protocol: smtp # 邮件协议
    host: smtp.163.com
    port: 25
    username: zz3297237645@163.com
    password: QYZPCGWJJVTVRQRU
    default-encoding: utf-8
    properties:
      mail:
        debug: true

knife4j:
  enable: true
  documents:
    -
      group: 小兔鲜儿管理系统_接口文档
      name: 求你看我！！ 必看必看！！！
      # 某一个文件夹下所有的.md文件
      locations: classpath:markdown/*.md
  setting:
    language: zh-CN
    enableDocumentManage: true
    enableSwaggerModels: true
    swaggerModelName: 实体类列表
    enableVersion: true
    enableReloadCacheParameter: false
    enableAfterScript: true
    #  #具体接口的过滤类型
    enableFilterMultipartApiMethodType: POST
    #  针对RequestMapping的接口请求类型,在不指定参数类型的情况下,如果不过滤,默认会显示7个类型的接口地址参数,如果开启此配置,默认展示一个Post类型的接口地址
    enableFilterMultipartApis: false
    #请求缓存
    enableRequestCache: true
    #开启  自定义Host
    #    enableHost: true
    #    enableHostText: "localhost:8004"
    #自定义主页
    #    enableHomeCustom: true
    #    homeCustomLocation: classpath*:markdown/home.md
    enableSearch: false
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: 小兔鲜儿商城
    enableDynamicParameter: true
    enableDebug: true
    enableOpenApi: true
    enableGroup: true
  cors: false
  production: false
  basic:
    enable: false
    username: admin
    password: 123123

springfox:
  documentation:
    open-api:
      enabled: true
# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: hzqewwesdSD
  # 令牌有效期（默认30分钟）
  expireTime: 30

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.qgj.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

qiniuyun:
  AccessKey: s23Q71L36NBDH21WNGXA8jleqGEe05qqMKcJ02Qj
  SecretKey: udcYCCvDVydWflpaGdt_OiMXXObVpPbb403_wzl-
  bucket: shopping-xxtr
  prefix: raay2lp2t.hn-bkt.clouddn.com
